**Importing Necessary Libraries**

In [11]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
x = torch.rand(7, 7)
y = torch.rand(1, 7)
torch.matmul(x, y.t())

tensor([[0.9454],
        [0.9473],
        [0.7089],
        [1.4405],
        [1.3714],
        [0.9152],
        [0.9704]])

In [13]:
# random seed to 0
torch.manual_seed(0)
x = torch.rand(7, 7)
y = torch.rand(1, 7)
torch.matmul(x, y.t())

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [14]:
torch.cuda.manual_seed(1234)
x = torch.rand(7, 7)
y = torch.rand(1, 7)
torch.matmul(x, y.t())

tensor([[1.2239],
        [2.0847],
        [1.9002],
        [0.9408],
        [1.5213],
        [1.3606],
        [0.8780]])

In [23]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2, 3)).to(device)
tensor_B = torch.rand(size=(2, 3)).to(device)
tensor_A, tensor_B

# Perform matmul on tensor_A and tensor_B
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

Device: cuda


(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [24]:
max = torch.max(tensor_C)
min = torch.min(tensor_C)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))